# Feature selection on Breast Caner Wisconsin (Classification Problem)

In [6]:
import pandas as pd
import numpy as np
import sys
sys.path.append("../src/UBayFS")

from UBaymodel import UBaymodel
from UBayconstraint import UBayconstraint

In [7]:
data = pd.read_csv("./data/data.csv")
labels = pd.read_csv("./data/labels.csv").replace(("M","B"),(0,1)).astype(int)

## Build UBaymodel

In [8]:
model = UBaymodel(data=data,
                 target = labels,
                 feat_names = data.columns,
                 weights = [0.01],
                 M = 5)

100%|██████████████████████████████████████████████████████████████████████████████████| 14/14 [00:00<00:00, 19.51it/s]


In [9]:
model.constraints

[]

In [11]:
model.getOptim()

{'method': ['mrmr'], 'popsize': 100, 'maxiter': 100}

In [5]:
model.ncol

30

In [6]:
weights = np.tile(np.array([10,15,20,16,15,10,12,17,21,14]),3)
strength = 1
weights = weights * strength / np.sum(weights)
weights
#print(weights.shape)
model.setWeights(weights)

In [7]:
model.getWeights()

array([0.02222222, 0.03333333, 0.04444444, 0.03555556, 0.03333333,
       0.02222222, 0.02666667, 0.03777778, 0.04666667, 0.03111111,
       0.02222222, 0.03333333, 0.04444444, 0.03555556, 0.03333333,
       0.02222222, 0.02666667, 0.03777778, 0.04666667, 0.03111111,
       0.02222222, 0.03333333, 0.04444444, 0.03555556, 0.03333333,
       0.02222222, 0.02666667, 0.03777778, 0.04666667, 0.03111111])

In [8]:
constraints = UBayconstraint(rho=np.array([np.Inf, 0.1, 1, 1]), 
                             constraint_types=["max_size", "must_link", "cannot_link", "cannot_link","jjj"], 
                             constraint_vars=[10, [0,10,20], [0,9], [19,22,23]], 
                             num_elements=data.shape[1])

In [9]:
model.setConstraints(constraints)

In [10]:
model.getConstraints()

{0: {'A': array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
           1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
           1.,  1.,  1.,  1.],
         [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  0.,  0.,
           0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
           0.,  0.,  0.,  0.],
         [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
           0.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  0.,  0.,  0.,  0.,  0.,
           0.,  0.,  0.,  0.],
         [-1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,
           0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
           0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,
           0.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  0.,  0.,  0.,  0.,  0.,
           0.,  0.,  0.,  0.],
         [-1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
           0

In [11]:
model.setOptim(method="GA", popsize=100, maxiter=200)

In [12]:
model.getOptim()

{'method': 'GA', 'popsize': 100, 'maxiter': 200}

In [13]:
model.train()

(                         0
 mean.radius              1
 mean.texture             0
 mean.perimeter           1
 mean.area                1
 mean.smoothness          0
 mean.compactness         0
 mean.concavity           0
 mean.concave.points      1
 mean.symmetry            0
 mean.fractal.dimension   0
 radius.error             1
 texture.error            0
 perimeter.error          1
 area.error               0
 smoothness.error         0
 compactness.error        0
 concavity.error          0
 concave.points.error     0
 symmetry.error           0
 fractal.dimension.error  0
 worst.radius             1
 worst.texture            0
 worst.perimeter          1
 worst.area               0
 worst.smoothness         1
 worst.compactness        0
 worst.concavity          0
 worst.concave.points     1
 worst.symmetry           0
 worst.fractal.dimension  0,
 ['mean.radius',
  'mean.perimeter',
  'mean.area',
  'mean.concave.points',
  'radius.error',
  'perimeter.error',
  'worst.radius

In [14]:
state = np.zeros(30)
state[[2,24,23]] = 1
model.evaluateFS(state=state)

{'cardinality': 3.0,
 'total utility': -0.854,
 'posterior feature utility': 0.146,
 'admissibility': 0.0,
 'number of violated constraints': 0,
 'average feature correlation': 0.449}

# Block model

## Version 1 with block list

In [15]:
block_list = [np.arange(0,10), np.arange(10,20), np.arange(20,30)]

In [16]:
block_constraints = UBayconstraint(rho=np.array([1]), 
                             constraint_types=["max_size"], 
                             constraint_vars=[1], 
                             num_elements=len(block_list),
                                block_list = block_list)

In [17]:
block_constraints.A

array([[1., 1., 1.]])

In [18]:
block_constraints.b

array([1.])

In [19]:
block_constraints.rho

array([1.])

In [20]:
pd.DataFrame(block_constraints.block_matrix)

0    1    2    3    4    5    6    7    8    9   ...   20   21   22   23  \
0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  ...  0.0  0.0  0.0  0.0   
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.0  1.0  1.0  1.0   

    24   25   26   27   28   29  
0  0.0  0.0  0.0  0.0  0.0  0.0  
1  0.0  0.0  0.0  0.0  0.0  0.0  
2  1.0  1.0  1.0  1.0  1.0  1.0  

[3 rows x 30 columns]

## Version 2 with block matrix

In [21]:
block_matrix = np.zeros((3, model.ncol))
block_matrix[0,np.arange(0,10)] = 1
block_matrix[1,np.arange(10,20)] = 1
block_matrix[2,np.arange(20,30)] = 1


In [22]:
pd.DataFrame(block_matrix)

0    1    2    3    4    5    6    7    8    9   ...   20   21   22   23  \
0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  ...  0.0  0.0  0.0  0.0   
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.0  1.0  1.0  1.0   

    24   25   26   27   28   29  
0  0.0  0.0  0.0  0.0  0.0  0.0  
1  0.0  0.0  0.0  0.0  0.0  0.0  
2  1.0  1.0  1.0  1.0  1.0  1.0  

[3 rows x 30 columns]

In [23]:
block_matrix.shape[1]

30

In [24]:
block_constraints_2 = UBayconstraint(rho=np.array([1]), 
                             constraint_types=["max_size", "must_link"], 
                             constraint_vars=[1,[1,2]], 
                             num_elements=3,
                                block_matrix = block_matrix)

In [25]:
# define block weights

def build_block_weights(blocks, weights):
    weights_ass = []
    for i in blocks:
        weights_ass.append(weights[i])
    return np.array(weights_ass)

In [26]:
prior_weights = build_block_weights(blocks = np.repeat([0,1,2], 10), weights=np.array([0.5,1,2]))

## Build model and add constraints

In [27]:
model = UBaymodel(data=data,
                 target = labels.values,
                 feat_names = data.columns,
                 weights = prior_weights,
                 nr_features = 10)

100%|██████████████████████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 61.12it/s]


In [28]:
pd.DataFrame(block_constraints.A)

0    1    2
0  1.0  1.0  1.0

In [29]:
pd.DataFrame(block_constraints_2.A)

0    1    2
0  1.0  1.0  1.0
1  0.0  1.0 -1.0
2  0.0 -1.0  1.0

In [30]:
model.setConstraints(block_constraints)
model.setConstraints(block_constraints_2, append=True)

# add max-size constraint
model.setConstraints(UBayconstraint(rho=np.array([1]), 
                             constraint_types=["max_size"], 
                             constraint_vars=[3], 
                             num_elements=model.ncol),
                    append=True)

In [31]:
model.getConstraints()

{0: {'A': array([[ 1.,  1.,  1.],
         [ 1.,  1.,  1.],
         [ 0.,  1., -1.],
         [ 0., -1.,  1.]]),
  'b': array([1., 1., 0., 0.]),
  'rho': array([1., 1., 1., 1.]),
  'block_matrix': array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
          1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])},
 1: {'A': array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
          1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]),
  'b': array([3.]),
  'rho': array([1.]),
  'block_matrix': array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0.

In [32]:
model.train()

(                         0
 mean.radius              0
 mean.texture             0
 mean.perimeter           0
 mean.area                1
 mean.smoothness          0
 mean.compactness         0
 mean.concavity           1
 mean.concave.points      1
 mean.symmetry            0
 mean.fractal.dimension   0
 radius.error             0
 texture.error            0
 perimeter.error          0
 area.error               0
 smoothness.error         0
 compactness.error        0
 concavity.error          0
 concave.points.error     0
 symmetry.error           0
 fractal.dimension.error  0
 worst.radius             0
 worst.texture            0
 worst.perimeter          0
 worst.area               0
 worst.smoothness         0
 worst.compactness        0
 worst.concavity          0
 worst.concave.points     0
 worst.symmetry           0
 worst.fractal.dimension  0,
 ['mean.area', 'mean.concavity', 'mean.concave.points'])

In [33]:
model.counts

mean.radius                100
mean.texture                 0
mean.perimeter             100
mean.area                  100
mean.smoothness              0
mean.compactness             0
mean.concavity             100
mean.concave.points        100
mean.symmetry                0
mean.fractal.dimension       0
radius.error                 0
texture.error                0
perimeter.error              0
area.error                   0
smoothness.error             0
compactness.error            0
concavity.error              0
concave.points.error         0
symmetry.error               0
fractal.dimension.error      1
worst.radius               100
worst.texture                0
worst.perimeter            100
worst.area                 100
worst.smoothness             0
worst.compactness            0
worst.concavity             99
worst.concave.points       100
worst.symmetry               0
worst.fractal.dimension      0
dtype: object

In [34]:
model.printConstraints()

AttributeError: 'UBaymodel' object has no attribute 'printConstraints'

In [ ]:
state = np.zeros(30)
state[[2,24,23]] = 1


In [ ]:
state

In [ ]:
model.constraints[0].A.shape

In [ ]:
np.sum(np.matmul(model.constraints[0].A, np.matmul(model.constraints[0].block_matrix, state)>0) > model.constraints[0].b)

In [ ]:
c = model.data.iloc[:,state==1].corr().values

In [ ]:
np.round((np.sum(c) - np.sum(np.diag(c))) / (np.sum(state) * (np.sum(state)-1)),3)